apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "2.4.0"
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    
    
    controllers:
      main:
        
        containers:
          main:
            
            image:
              repository: lscr.io/linuxserver/radarr
              tag: latest
            
            
            env:
              PUID: "0"
              PGID: "0"
              TZ: "America/Sao_Paulo"

    
    service:
      main:
        ports:
          http:
            port: 7878 
    
    ingress:
      main: 
        enabled: true
        className: "nginx" 
        hosts:
          - host: radarr.franch.in
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - radarr.franch.in
            secretName: radarr-tls
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"

    
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/configs/radarr
        mountPath: /config 
      
      downloads:
        enabled: true
        type: hostPath
        hostPath: /mnt/downloads
        mountPath: /downloads
      
      movies: 
        enabled: true
        type: hostPath
        hostPath: /mnt/media/movies
        mountPath: /movies

    
    
    
    
    
    