apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2"
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/qbittorrent
              tag: "latest"
            env:
              PUID: "1000"
              PGID: "1000"
              WEBUI_UP: "true"
              WEBUI_USERNAME: "admin"
              WEBUI_PASSWORD: "changeme"
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: qbittorrent.franch.in
            paths: [{ path: /, pathType: Prefix }]
        tls:
          - secretName: qbittorrent-tls
            hosts: [qbittorrent.franch.in]
        annotations: { cert-manager.io/cluster-issuer: "letsencrypt-production" }
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/configs/qbittorrent
        advancedMounts:
          main: 
            main: 
              - path: /config 
      downloads:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/data/downloads
        advancedMounts:
          main: 
            main: 
              - path: /downloads 