apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "2.4.0"
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    image: { repository: lscr.io/linuxserver/qbittorrent, tag: "4.6.3" }
    env:
      PUID: "0"
      PGID: "0"
      TZ: "America/Sao_Paulo"
      WEBUI_UP: "true" 
      WEBUI_USERNAME: "admin"
      WEBUI_PASSWORD: "changeme"
    ingress:
      enabled: true
      hosts:
        - host: qbittorrent.franch.in
          paths: [{ path: /, pathType: Prefix }]
      tls:
        - secretName: qbittorrent-tls
          hosts: [qbittorrent.franch.in]
      annotations: { cert-manager.io/cluster-issuer: "letsencrypt-production" }
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/configs/qbittorrent
      # downloads:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /mnt/downloads