apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gui.franchin12@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production-key
    solvers:
    - http01:
        ingress:
          class: nginx
