apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.1.2" 
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    fullnameOverride: "prometheus" 
    grafana:
      enabled: true
      adminPassword: "changeme"
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - "grafana.franch.in"
        path: /
        tls:
          - secretName: grafana-tls
            hosts:
              - "grafana.franch.in"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
      persistence:
        enabled: true
        type: pvc 
        storageClassName: "local-path" 
        size: 5Gi
        accessModes:
          - ReadWriteOnce
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "local-path" 
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      enabled: false 
    prometheus-node-exporter:
      enabled: true
    kube-state-metrics:
      enabled: true