apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/prowlarr]
              tag: latest
            env:
              PUID: "0"
              PGID: "0"
              TZ: "America/Sao_Paulo"
    service:
      main:
        ports:
          http:
            port: 9696]
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: prowlarr.franch.in]
            paths: [{ path: /, pathType: Prefix }]
        tls:
          - secretName: prowlarr-tls]
            hosts: [prowlarr.franch.in]
        annotations: { cert-manager.io/cluster-issuer: "letsencrypt-production" }
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/configs/prowlarr]
        mountPath: /config