apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jackett
  namespace: automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2" 
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/jackett
              tag: latest
    service:
      main:
        ports:
          http:
            port: 9117 
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: jackett.franch.in
            paths: [{ path: /, pathType: Prefix }]
        tls:
          - secretName: jackett-tls
            hosts: [jackett.franch.in]
        annotations: { cert-manager.io/cluster-issuer: "letsencrypt-production" }
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/configs/jackett
        mountPath: /config
      # downloads:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /mnt/downloads
      #   mountPath: /downloads