apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "2.4.0"
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    image: { repository: lscr.io/linuxserver/jackett, tag: latest }
    ingress:
      enabled: true
      hosts:
        - host: jackett.franch.in
          paths: [{ path: /, pathType: Prefix }]
      tls:
        - secretName: jackett-tls
          hosts: [jackett.franch.in]
      annotations: { cert-manager.io/cluster-issuer: "letsencrypt-production" }
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/configs/jackett
      # downloads:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /mnt/downloads