apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2" 
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/overseerr
              tag: latest
            env:
              PUID: "0"
              PGID: "0"
              TZ: "America/Sao_Paulo"
    service:
      main:
        ports:
          http:
            port: 5055 
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: requests.franch.in
            paths: [{ path: /, pathType: Prefix }]
        tls:
          - secretName: overseerr-tls
            hosts: [requests.franch.in]
        annotations: { cert-manager.io/cluster-issuer: "letsencrypt-production" }
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/configs/overseerr
        advancedMounts:
          main:
            main:
              - path: /config