apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2"
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/sonarr
              tag: latest
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: "America/Sao_Paulo"
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: sonarr.franch.in
            paths: [{ path: /, pathType: Prefix }]
        tls:
          - secretName: sonarr-tls
            hosts: [sonarr.franch.in]
        annotations: { cert-manager.io/cluster-issuer: "letsencrypt-production" }
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/configs/sonarr
        advancedMounts:
          main:
            main:
              - path: /config
      downloads:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/data/downloads 
        advancedMounts:
          main:
            main:
              - path: /downloads
      media:
        enabled: true
        type: hostPath
        hostPath: /mnt/media
        advancedMounts:
          main:
            main:
              - path: /media 
