apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/core/cert-manager-config
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  wait: true 
  dependsOn:
    - name: cert-manager
      namespace: cert-manager