# cluster/orchestration/infrastructure.yaml (VERSÃO FINAL E CORRETA)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/infrastructure
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  dependsOn:
    - name: repositories
  healthChecks:  
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ingress-nginx
      namespace: networking  
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager