apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: gaming
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2"
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: itzg/minecraft-server
              tag: java21-jdk
            env:
              EULA: "TRUE"
              TYPE: "VANILLA"
              VERSION: "1.21.7"
              MEMORY: "1536M"
            resources:
              requests: { cpu: "250m", memory: "1Gi" }
              limits: { cpu: "1500m", memory: "2Gi" }
            tty: true
            stdin: true
    service:
      main:
        type: LoadBalancer
        ports:
          minecraft:
            enabled: true
            port: 25565
            protocol: TCP
            targetPort: 25565

    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/data/minecraft
        advancedMounts:
          main:
            main:
              - path: /data