apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef: {kind: HelmRepository, name: bjw-s-charts, namespace: flux-system}
  values:
    image: {repository: lscr.io/linuxserver/plex, tag: latest}
    service:
      main: {ports: {http: {port: 32400}}}
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: "plex.franch.in"
          paths:
          - {path: /, pathType: Prefix}
        tls:
        - secretName: plex-tls-cert
          hosts:
          - "plex.franch.in"
    persistence:
      config: {enabled: true, mountPath: /config, type: hostPath, hostPath: /srv/k3s/configs/plex}
      media: {enabled: true, mountPath: /media, type: hostPath, hostPath: /mnt/media}
      transcode: {enabled: true, type: hostPath, hostPath: /srv/k3s/configs/plex/transcode}
    env: {TZ: "America/Sao_Paulo"}
