apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  releaseName: plex
  chart:
    spec:
      chart: plex-media-server
      version: "1.0.2"
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    extraEnv:
      PLEX_CLAIM: "claim-YXtPvvr3JrKnQbmMuMq2"
    pms:
      securityContext:
        privileged: true
    ingress:
      enabled: true
      ingressClassName: "nginx" 
      hosts:
        - host: plex.franch.in
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: plex-tls-cert
          hosts:
            - plex.franch.in
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/configs/plex
      transcode:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/configs/plex/transcode
    additionalVolumes:
      - name: media
        hostPath:
          path: /mnt/media
    additionalVolumeMounts:
      - name: media
        mountPath: /media