apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2" 
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/plex
              tag: latest
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: "America/Sao_Paulo"
              PLEX_CLAIM: "claim-cYd6p4yjWTXizFx3Z6nq" 
            securityContext:
              privileged: false
              devices:
                - /dev/dri:/dev/dri 
    service:
      main:
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: plex.franch.in
            paths: [{ path: /, pathType: Prefix }]
        tls:
          - secretName: plex-tls-cert
            hosts: [plex.franch.in]
        annotations: { cert-manager.io/cluster-issuer: "letsencrypt-production" }
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/configs/plex 
        advancedMounts:
          main:
            main:
              - path: /config
      transcode:
        enabled: true
        type: emptyDir 
      # media:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /mnt/media 
      #   advancedMounts:
      #     main:
      #       main:
      #         - path: /media
      downloads:
        enabled: true
        type: hostPath
        hostPath: /srv/k3s/data/downloads 
        advancedMounts:
          main:
            main:
              - path: /downloads
                readOnly: true