apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: gaming
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2"
      sourceRef: { kind: HelmRepository, name: bjw-s-labs, namespace: flux-system }
  values:
    service:
      main:
        type: LoadBalancer
        ports:
          minecraft:
            enabled: true
            port: 25565
            protocol: TCP
            targetPort: 25565 
    controllers:
      main:
        pod:
          serviceAccount:
            create: true
            name: minecraft-proxy 
        containers:
          main:
            image:
              repository: itzg/mc-router
              tag: latest
            env:
              PROXY_TO_HOST: "minecraft-server.gaming.svc.cluster.local"
              PROXY_TO_PORT: "25565" 
              MODE: "autostart"
              KUBERNETES_SELECTOR: "mc-autoshutdown=true"
              KUBERNETES_NAMESPACE: "gaming"
              SHUTDOWN_TIMEOUT_SECONDS: "600"