apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-warden
  namespace: gaming
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft-kubernetes-warden
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: wardens
        namespace: flux-system
  values:
    watchdog:
      namespace: gaming
      labelSelector: "app.kubernetes.io/instance=minecraft" 
    mcProxy:
      enabled: false